export const RELAY_APP_CONFIG = {
  APP: process.env.RELAY_CONFIG_RECIPIENT_ADDRESS!,
  FEE: process.env.RELAY_CONFIG_FEE, // IN BASIS POINTS 100 = 1%
  TRADE_TYPE: {
    EXACT_INPUT: "EXACT_INPUT",
    EXACT_OUTPUT: "EXACT_OUTPUT",
    EXPECTED_OUTPUT: "EXPECTED_OUTPUT",
  },
}
