/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    articles: Article;
    categories: Category;
    faqs: Faq;
    heroes: Hero;
    logos: Logo;
    services: Service;
    steps: Step;
    testimonials: Testimonial;
    'trade-coins': TradeCoin;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      articles: 'articles';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    heroes: HeroesSelect<false> | HeroesSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    steps: StepsSelect<false> | StepsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'trade-coins': TradeCoinsSelect<false> | TradeCoinsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    global: Global;
  };
  globalsSelect: {
    global: GlobalSelect<false> | GlobalSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * URL segment.
   */
  slug: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaImage?: (number | null) | Media;
    keywords?: string | null;
    metaRobots?: string | null;
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    metaViewport?: string | null;
    canonicalURL?: string | null;
  };
  dynamic_zone?:
    | (
        | {
            heading?: string | null;
            sub_heading?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamic-zone__testimonials';
          }
        | {
            heading?: string | null;
            sub_heading?: string | null;
            faqs?: (number | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamic-zone__faq';
          }
        | {
            coins?: (number | Logo)[] | null;
            trade_coin?: (number | null) | TradeCoin;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamic-zone__discover-coins';
          }
        | {
            services?: (number | Service)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamic-zone__services';
          }
        | {
            step?: (number | null) | Step;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamic-zone__steps';
          }
        | {
            hero?: (number | null) | Hero;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamic-zone__hero';
          }
        | {
            heading?: string | null;
            sub_heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'shared__header';
          }
        | {
            /**
             * Markdown
             */
            content?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamic-zone__content';
          }
        | {
            contacts?:
              | {
                  title?: string | null;
                  description?: string | null;
                  button?: {
                    text?: string | null;
                    URL?: string | null;
                    target?: ('_blank' | '_self' | '_parent' | '_top') | null;
                    description?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            community?:
              | {
                  title?: string | null;
                  description?: string | null;
                  button?: {
                    text?: string | null;
                    URL?: string | null;
                    target?: ('_blank' | '_self' | '_parent' | '_top') | null;
                    variant?: ('default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamic-zone__contact';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  text?: string | null;
  user?: {
    name?: string | null;
    country?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer?: string | null;
  category?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  articles?: {
    docs?: (number | Article)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  faqs?: (number | Faq)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Markdown
   */
  content?: string | null;
  image?: (number | null) | Media;
  categories?: (number | Category)[] | null;
  featured?: boolean | null;
  /**
   * URL segment. Generated from the title if left empty.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  company?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-coins".
 */
export interface TradeCoin {
  id: number;
  heading?: string | null;
  sub_heading?: string | null;
  tag?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  heading?: string | null;
  sub_heading?: string | null;
  live_support_card?: {
    title?: string | null;
    description?: string | null;
    span?: ('one' | 'two' | 'three') | null;
  };
  market_rate_card?: {
    title?: string | null;
    description?: string | null;
    span?: ('one' | 'two' | 'three') | null;
  };
  secure_card?: {
    title?: string | null;
    description?: string | null;
    span?: ('one' | 'two' | 'three') | null;
  };
  transaction_card?: {
    title?: string | null;
    description?: string | null;
    span?: ('one' | 'two' | 'three') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "steps".
 */
export interface Step {
  id: number;
  heading?: string | null;
  sub_heading?: string | null;
  steps?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroes".
 */
export interface Hero {
  id: number;
  heading?: string | null;
  sub_heading?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'heroes';
        value: number | Hero;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'steps';
        value: number | Step;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'trade-coins';
        value: number | TradeCoin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        keywords?: T;
        metaRobots?: T;
        structuredData?: T;
        metaViewport?: T;
        canonicalURL?: T;
      };
  dynamic_zone?:
    | T
    | {
        'dynamic-zone__testimonials'?:
          | T
          | {
              heading?: T;
              sub_heading?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        'dynamic-zone__faq'?:
          | T
          | {
              heading?: T;
              sub_heading?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        'dynamic-zone__discover-coins'?:
          | T
          | {
              coins?: T;
              trade_coin?: T;
              id?: T;
              blockName?: T;
            };
        'dynamic-zone__services'?:
          | T
          | {
              services?: T;
              id?: T;
              blockName?: T;
            };
        'dynamic-zone__steps'?:
          | T
          | {
              step?: T;
              id?: T;
              blockName?: T;
            };
        'dynamic-zone__hero'?:
          | T
          | {
              hero?: T;
              id?: T;
              blockName?: T;
            };
        shared__header?:
          | T
          | {
              heading?: T;
              sub_heading?: T;
              id?: T;
              blockName?: T;
            };
        'dynamic-zone__content'?:
          | T
          | {
              content?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'dynamic-zone__contact'?:
          | T
          | {
              contacts?:
                | T
                | {
                    title?: T;
                    description?: T;
                    button?:
                      | T
                      | {
                          text?: T;
                          URL?: T;
                          target?: T;
                          description?: T;
                        };
                    id?: T;
                  };
              community?:
                | T
                | {
                    title?: T;
                    description?: T;
                    button?:
                      | T
                      | {
                          text?: T;
                          URL?: T;
                          target?: T;
                          variant?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  image?: T;
  categories?: T;
  featured?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  articles?: T;
  faqs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroes_select".
 */
export interface HeroesSelect<T extends boolean = true> {
  heading?: T;
  sub_heading?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  company?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  heading?: T;
  sub_heading?: T;
  live_support_card?:
    | T
    | {
        title?: T;
        description?: T;
        span?: T;
      };
  market_rate_card?:
    | T
    | {
        title?: T;
        description?: T;
        span?: T;
      };
  secure_card?:
    | T
    | {
        title?: T;
        description?: T;
        span?: T;
      };
  transaction_card?:
    | T
    | {
        title?: T;
        description?: T;
        span?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "steps_select".
 */
export interface StepsSelect<T extends boolean = true> {
  heading?: T;
  sub_heading?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  text?: T;
  user?:
    | T
    | {
        name?: T;
        country?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-coins_select".
 */
export interface TradeCoinsSelect<T extends boolean = true> {
  heading?: T;
  sub_heading?: T;
  tag?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global".
 */
export interface Global {
  id: number;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaImage?: (number | null) | Media;
    keywords?: string | null;
    metaRobots?: string | null;
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    metaViewport?: string | null;
    canonicalURL?: string | null;
  };
  navbar?: {
    logo?: (number | null) | Logo;
    items?:
      | {
          title?: string | null;
          items?:
            | {
                text?: string | null;
                URL?: string | null;
                target?: ('_blank' | '_self' | '_parent' | '_top') | null;
                description?: string | null;
                id?: string | null;
              }[]
            | null;
          key?: ('business' | 'services') | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    logo?: (number | null) | Logo;
    description?: string | null;
    copyright?: string | null;
    columns?:
      | {
          title?: string | null;
          items?:
            | {
                text?: string | null;
                URL?: string | null;
                target?: ('_blank' | '_self' | '_parent' | '_top') | null;
                description?: string | null;
                id?: string | null;
              }[]
            | null;
          key?: ('business' | 'services') | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    email?: string | null;
    social_media_links?:
      | {
          text?: string | null;
          URL?: string | null;
          target?: ('_blank' | '_self' | '_parent' | '_top') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global_select".
 */
export interface GlobalSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        keywords?: T;
        metaRobots?: T;
        structuredData?: T;
        metaViewport?: T;
        canonicalURL?: T;
      };
  navbar?:
    | T
    | {
        logo?: T;
        items?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    URL?: T;
                    target?: T;
                    description?: T;
                    id?: T;
                  };
              key?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        logo?: T;
        description?: T;
        copyright?: T;
        columns?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    URL?: T;
                    target?: T;
                    description?: T;
                    id?: T;
                  };
              key?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        email?: T;
        social_media_links?:
          | T
          | {
              text?: T;
              URL?: T;
              target?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}